title: Austinzhenyu Lin's Homepage
page-top-title: Zhenyu Lin
top-section-bg-text: 你好！欢迎来到我的主页！
home-subtitle: Zhenyu Lin&ensp;|&ensp;林振宇
copyright-text: '&copy; Austinzhenyu Lin 2026-2030. All Rights Reserved.'
